#include "shapes.h"

void drawA();
void drawB();
void drawC();
void drawD();
void drawE();
void drawF();
void drawG();
void drawH();
void drawI();
void drawJ();
void drawK();
void drawL();
void drawM();
void drawN();
void drawO();
void drawP();
void drawQ();
void drawR();
void drawS();
void drawT();
void drawU();
void drawV();
void drawW();
void drawX();
void drawY();
void drawZ();
void drawLetter(char letter);